name: 'NPM Custom Action'
description: 'Installing and Caching NPM packages'
input:
  path-of-folder:
    description: 'The path to cache'
    required: true
runs:
  using: "composite"
  steps:
  - name: Cache NPM Dependencies
    uses: actions/cache@v4
    with:
      path: ${{ inputs.path-of-folder }}
      key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
  
  - name: Install Dependencies
    run: npm install